@BIM.API_HostAddress = https://localhost:7209



###

POST {{BIM.API_HostAddress}}/api/books
Content-Type: application/json

{
      "title": "The Man",
      "author": "Arshad Ahamed",
      "genre": "Classic Fiction",
      "isbn": "9780743273575",
      "publishedDate": "1935-04-10T00:00:00",
      "price": 1100.00,
      "quantity": 10
}

###

GET {{BIM.API_HostAddress}}/api/books?searchPharse=&pageSize=5&pageNumber=1

###

GET {{BIM.API_HostAddress}}/api/books/2

###

DELETE {{BIM.API_HostAddress}}/api/books/2

###

PATCH {{BIM.API_HostAddress}}/api/books/{id}
Content-Type: application/json

{
  //UpdateBookCommand
}

###
