@BIM.API_HostAddress = https://localhost:7209
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIiwianRpIjoiMjdiOTY0MmMtOTg1Ny00MTgzLTlmYTQtYmM0MzRmMmY3ZTVlIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTczMzU4MDY1OSwiaXNzIjoiRnJlZVRyYWluZWQifQ.uRNB19v9x0ugsxN5mXSFyI4xMHz4zXi4laNZKVGwjok

GET {{BIM.API_HostAddress}}/api/books

###

POST {{BIM.API_HostAddress}}/api/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "title": "Wooow",
      "author": "Fathima",
      "genre": "Fiction",
      "isbn": "9980743273225",
      "publishedDate": "2024-04-10T00:00:00",
      "price": 3000.00,
      "quantity": 10
}

###

GET {{BIM.API_HostAddress}}/api/books/5
Authorization: Bearer {{token}}

###

DELETE {{BIM.API_HostAddress}}/api/books/1009

###

PATCH {{BIM.API_HostAddress}}/api/books/1
Content-Type: application/json

{
      "title": "The One Man"
     
    
}

###

GET {{BIM.API_HostAddress}}/api/books/matching?searchPharse=Man&pageSize=5&pageNumber=1

###


GET {{BIM.API_HostAddress}}/api/books/search?keywords=Ar
###

PATCH {{BIM.API_HostAddress}}/api/books/5
Content-Type: application/json
{
  "author": "Super Man"
}



###

POST {{BIM.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}

###

POST {{BIM.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}

###



POST {{BIM.API_HostAddress}}/api/account/register
Content-Type: application/json

{
  "Email" : "arshad@gmail.com",
  "Password" : "Arshad@12345",
  "Role": "User"
}


###

POST {{BIM.API_HostAddress}}/api/account/add-role
Content-Type: application/json

"string"

###

POST {{BIM.API_HostAddress}}/api/account/assign-role
Content-Type: application/json

{
  "username": "Arshad",
  "role": "Admin"
}

###

POST {{BIM.API_HostAddress}}/api/account/login
Content-Type: application/json

{
  //LoginDto
}

###

POST {{BIM.API_HostAddress}}/api/account/register
Content-Type: application/json

{
  "username": "Arshad",
  "email": "Arshad@gmail.com",
  "password": "Arshad@123"
}

###

POST {{BIM.API_HostAddress}}/api/account/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "Admin@123"
}
###

POST {{BIM.API_HostAddress}}/api/account/login
Content-Type: application/json

{
  "username": "User",
  "password": "User@123"
}

###

POST {{BIM.API_HostAddress}}/api/books
Content-Type: application/json

{
  //CreateBookCommand
}

###

POST {{BIM.API_HostAddress}}/api/books
Content-Type: application/json

{
  //CreateBookCommand
}

###
